linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - musttag
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

    # These are disabled because they do not support Generics, yet.
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
